### ISSUE TITLE
Question about Bit-Parallelism MCE

### ISSUE THREAD

**Issue by zjw964** [darrenstrash/quick-cliques#6]
Hi,

I just read the paper you wrote in 2017, the title is "Efficiently Enumerating all Maximal Cliques with Bit-Parallelism", and I have a few questions to ask:
1、does it has the source code in github?
2、I find it is faster than the algorithm by Eppstein et al. but does it faster than some parallel solutions such as Shared-Memory Parallel Maximal Clique Enumeration by Apurba Das, Seyed-Vahid Sanei-Mehri, and Srikanta Tirthapura, https://export.arxiv.org/pdf/1807.09417.pdf? Do you have research？

Looking forward to your reply.
Great work by the way.

Cheers,

**Comment by darrenstrash** [comment]
Thanks for the questions, I'm happy to answer:

1. The source code for "Efficiently Enumerating all Maximal Cliques with Bit-Parallelism" can be found here: [https://github.com/psanse/clique_enum](https://github.com/psanse/clique_enum)
2. There is no direct comparison against the algorithm by Das, Sanei-Mehri, and Tirthapura that I am aware of, but such a comparison would be like comparing apples to oranges: their algorithm is shared-memory parallel -- running on multiple cores/cpus in a single machine -- and designed for large sparse graphs. Ours is only bit-parallel: it runs on the same core of the same CPU, but uses bit tricks to speed up the algorithm by a factor, and is intended for small dense graphs. You can expect a small factor speed up in our use case, and scaling with cores for theirs. I think a fair comparison is not possible, since they are designed for such different graphs and different use cases.

Best,
Darren
